feat: support dim preview
linuxdeepin/dcc-insider-plugin pull request #6
Opened 2023-12-29 08:23 UTC by zsien

support dim preview

2024-01-03 05:39 UTC, dengbo11 approved these changes

2024-01-04 07:30 UTC, dengbo11 commented
/integrate

2024-01-04 09:47 UTC, dengbo11 commented
/topic deepin-im

2024-01-04 09:48 UTC, dengbo11 commented
/integr-topic deepin-im

2024-01-05 02:57 UTC, dengbo11 commented
/integr-topic deepin-im

2024-01-05 03:28 UTC, dengbo11 commented
/integr-topic deepin-im

2024-01-05 03:33 UTC, dengbo11 commented
/retest

2024-01-05 06:31 UTC, justforlxz requested changes

2024-01-05 06:31 UTC, justforlxz commented on insidermodule.cpp
> +    if (file.exists()) {
open

2024-01-05 06:43 UTC, zsien commented on insidermodule.cpp
> +    if (file.exists()) {
done

2024-01-05 07:24 UTC, justforlxz approved these changes

2024-01-05 07:26 UTC, zsien commented
/merge

2024-01-05 07:26 UTC, merged